name: Newman API Tests

on:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: ./assignment3_204
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: "Install newman"
        run: "npm install -g newman"

      - name: "Run tests"
        run: "newman run New_Collection.postman_collection.json"

    if: always()

    with:
      name: testrun-report
      path: assignment3_204/assignment3_204
      retention-days: 30

    name: Slack Notification
    uses: rtCamp/action-slack-notify@v2
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_USERNAME: zi sheng teh
      SLACK_TITLE: assignment3
      SLACK_MESSAGE: "New change:rocket:"
