name: Newman API Tests
on:
  workflow_dispatch:
jobs:
  test:
    defaults:
      run:
        working-directory: ./assignment3_204
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install newman and reporters
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run tests
        run: |
          newman run New_Collection.postman_collection.json \
          -r cli,htmlextra,json,junit \
          --reporter-htmlextra-export ./newman-report.html \
          --reporter-json-export ./newman-report.json \
          --reporter-junit-export ./newman-report.xml
      - name: List generated files
        run: ls -l
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: testrun-report
          path: |
            ./newman-report.html
            ./newman-report.json
            ./newman-report.xml
          retention-days: 30
          if-no-files-found: warn
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: zi sheng teh
          SLACK_TITLE: assignment3
          SLACK_MESSAGE: "New change:rocket:"
