name: Newman API Tests
on: 
  workflow_dispatch:
jobs: 
  test: 
    defaults: 
      run: 
        working-directory: ./assignment3_204
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with: 
          node-version: "18"
      
      - name: "Install newman"
        run: "npm install -g newman"
      
      - name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      
      - name: "Run tests"
        run: |
          newman run New_Collection.postman_collection.json -r htmlextra \
          --reporter-htmlextra-export newman-report.html \
          --reporter-htmlextra-darkTheme
      
      - name: Archive Newman Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: ./assignment3_204/newman-report.html
      
      - name: Publish report to Slack
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          file_path: './assignment3_204/newman-report.html'
          file_name: 'newman-report.html'
          file_type: 'html'
          channels: 'test'
