name: Newman API Tests

on:
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: ./assignment3_204
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install newman
        run: npm install -g newman

      - name: Run tests
        run: newman run New_Collection.postman_collection.json

      - name: List directory contents
        run: ls -R ./assignment3_204 || echo "Directory ./assignment3_204 does not exist"

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: testrun-report
          path: assignment3_204/
          retention-days: 30
          if-no-files-found: warn
          compression-level: 6
          overwrite: false

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: zi sheng teh
          SLACK_TITLE: assignment3
          SLACK_MESSAGE: "New change:rocket:"
